-- Cotizador DEX 2.3 · Historial compartido de cotizaciones
-- Ejecutar una sola vez en Supabase > SQL Editor.

create table if not exists public.dex_cotizaciones (
  id bigint generated by default as identity primary key,
  folio text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cliente text,
  contacto text,
  titulo text,
  solicitud_cliente text,
  modalidad text,
  duracion text,
  participantes text,
  plantilla text default 'A',
  estado text not null default 'Borrador',
  monto_cotizado numeric(14,2) not null default 0,
  monto_contratado numeric(14,2),
  vendedor text,
  data jsonb not null default '{}'::jsonb
);

create index if not exists dex_cotizaciones_created_at_idx on public.dex_cotizaciones (created_at desc);
create index if not exists dex_cotizaciones_cliente_idx on public.dex_cotizaciones (cliente);
create index if not exists dex_cotizaciones_titulo_idx on public.dex_cotizaciones (titulo);
create index if not exists dex_cotizaciones_estado_idx on public.dex_cotizaciones (estado);

create or replace function public.set_dex_cotizaciones_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_dex_cotizaciones_updated_at on public.dex_cotizaciones;
create trigger trg_dex_cotizaciones_updated_at
before update on public.dex_cotizaciones
for each row execute function public.set_dex_cotizaciones_updated_at();

-- El backend usa la Service Role Key desde Render, por lo que no exponemos
-- credenciales ni hacemos escrituras directas desde el navegador.
alter table public.dex_cotizaciones enable row level security;
